### ISSUE TITLE
Getting several lints `clippy::pedantic`-enabled lints from generated code

### ISSUE THREAD

**Issue by lyssieth** [Kijewski/nate#52]
The specific lints I was able to pick out:

- [`clippy::used_underscore_binding`](https://rust-lang.github.io/rust-clippy/master/index.html#used_underscore_binding)
- [`clippy::uninlined_format_args`](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args)

**Comment by Kijewski** [comment]
Thank you for the bug report! I opened #53.
